### ISSUE TITLE
wrong orderbook order

### ISSUE THREAD

**Issue by phideas** [chainmakers/chainmakers-ui-mono-repository#37]
MM2: 2.0.1095_mm2_8cf193c18_Linux 
Application: Chainswap Application 0.23.4
Electron: 4.1.3
OS: linux 4.15.0-58-generic
Locale: en-US

if someone wants to buy kmd with usdc, the app shows the most expensive offer, not the cheapest one. screenshot: https://imgur.com/a/DfZPRTQ

**Comment by particle4dev** [comment]
Thanks for reporting @phideas
I fixed it
We will include this in the next release!
